import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { BlogPostStatus } from '@prisma/client';

import { PrismaService } from '../../database/prisma.service';
import { BlogPostService } from '../blog/blog-post.service';
import { generateSlug, generateUniqueSlug } from '../blog/utils/slug.util';
import { CATEGORY_SEEDS } from './seed-topics';
import { ContentWriterService, GeneratedPost } from './content-writer.service';
import { QualityGateService } from './quality-gate.service';
import { ImagePickerService } from './image-picker.service';
import { TopicPlannerService } from './topic-planner.service';

export interface GenerationOutcome {
  status: 'published' | 'draft' | 'skipped' | 'failed';
  postId?: string;
  slug?: string;
  issues?: string[];
  error?: string;
}

@Injectable()
export class BlogGeneratorService {
  private readonly logger = new Logger(BlogGeneratorService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
    private readonly planner: TopicPlannerService,
    private readonly writer: ContentWriterService,
    private readonly quality: QualityGateService,
    private readonly imagePicker: ImagePickerService,
    private readonly blogPosts: BlogPostService,
  ) {}

  isEnabled(): boolean {
    return this.config.get<string>('BLOG_AUTOGEN_ENABLED') === 'true';
  }

  async generateOne(options: { dryRun?: boolean } = {}): Promise<GenerationOutcome> {
    const startedAt = Date.now();
    const kernel = this.planner.pickKernel();

    const log: any = {
      category: kernel.category.slug,
      intent: kernel.intent.slug,
      angle: kernel.angle.slug,
    };

    try {
      const titles = await this.planner.recentPostTitles(200);
      const { data: post, inputTokens, outputTokens, model } = await this.writer.write(kernel, titles);

      log.model = model;
      log.inputTokens = inputTokens;
      log.outputTokens = outputTokens;
      log.topic = post.title;

      const quality = this.quality.evaluate(post, kernel);

      if (options.dryRun) {
        return {
          status: quality.pass ? 'published' : 'draft',
          slug: post.slug,
          issues: quality.issues.length ? quality.issues : undefined,
        };
      }

      const botUserId = this.config.get<string>('BLOG_BOT_USER_ID');

      if (!botUserId) {
        await this.writeLog({ ...log, status: 'FAILED', durationMs: Date.now() - startedAt, errorCode: 'NO_BOT_USER', errorMessage: 'BLOG_BOT_USER_ID not set' });

        return { status: 'failed', error: 'BLOG_BOT_USER_ID not set' };
      }

      const slug = await this.resolveSlug(post);

      if (!slug) {
        await this.writeLog({ ...log, status: 'SKIPPED', durationMs: Date.now() - startedAt, errorCode: 'SLUG_CONFLICT', errorMessage: 'could not derive unique slug' });

        return { status: 'skipped', error: 'slug conflict' };
      }

      const image = await this.imagePicker.pick(post.imageQuery, kernel.category.slug, post.featuredImageAlt);
      const categoryId = await this.resolveCategoryId(kernel.category.slug);
      const tagIds = await this.resolveTagIds(post.tags);

      const dto = {
        title: post.title.slice(0, 500),
        content: post.content,
        excerpt: post.excerpt?.slice(0, 1000),
        featuredImage: image.url,
        ogImage: image.url,
        status: quality.pass ? BlogPostStatus.PUBLISHED : BlogPostStatus.DRAFT,
        categoryId,
        tagIds,
        seoTitle: post.seoTitle?.slice(0, 255),
        seoDescription: post.seoDescription?.slice(0, 500),
        seoKeywords: post.seoKeywords?.slice(0, 500),
        faqItems: post.faqItems,
        howtoSteps: post.howtoSteps?.length ? post.howtoSteps : undefined,
      };

      const created = await this.blogPosts.create(botUserId, dto as any);

      await this.prisma.blogPost.update({
        where: { id: created.id },
        data: { isAutoGenerated: true, slug },
      });

      await this.writeLog({
        ...log,
        status: quality.pass ? 'PUBLISHED' : 'DRAFT',
        postId: created.id,
        slug,
        durationMs: Date.now() - startedAt,
        errorMessage: quality.pass ? null : quality.issues.join('; '),
      });

      return {
        status: quality.pass ? 'published' : 'draft',
        postId: created.id,
        slug,
        issues: quality.pass ? undefined : quality.issues,
      };
    } catch (err) {
      const message = (err as Error).message;

      this.logger.error(`Generation failed: ${message}`);
      await this.writeLog({ ...log, status: 'FAILED', durationMs: Date.now() - startedAt, errorCode: 'EXCEPTION', errorMessage: message.slice(0, 1000) });

      return { status: 'failed', error: message };
    }
  }

  async stats(days = 7) {
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);

    const logs = await this.prisma.blogGenerationLog.findMany({
      where: { createdAt: { gte: since } },
      orderBy: { createdAt: 'desc' },
    });

    const counts = logs.reduce<Record<string, number>>((acc, l) => {
      acc[l.status] = (acc[l.status] || 0) + 1;

      return acc;
    }, {});

    const totalInputTokens = logs.reduce((s, l) => s + (l.inputTokens || 0), 0);
    const totalOutputTokens = logs.reduce((s, l) => s + (l.outputTokens || 0), 0);
    const avgDuration = logs.length ? Math.round(logs.reduce((s, l) => s + (l.durationMs || 0), 0) / logs.length) : 0;

    return {
      windowDays: days,
      totalRuns: logs.length,
      counts,
      totalInputTokens,
      totalOutputTokens,
      avgDurationMs: avgDuration,
      recent: logs.slice(0, 25),
    };
  }

  private async resolveSlug(post: GeneratedPost): Promise<string | null> {
    const base = generateSlug(post.slug || post.title).slice(0, 80);

    if (!base) return null;

    const exists = await this.planner.existingSlug(base);

    if (!exists) return base;

    const alt = generateUniqueSlug(post.title).slice(0, 80);

    return (await this.planner.existingSlug(alt)) ? null : alt;
  }

  private async resolveCategoryId(slug: string): Promise<string | undefined> {
    const seed = CATEGORY_SEEDS.find(c => c.slug === slug);

    if (!seed) return undefined;

    const found = await this.prisma.blogCategory.upsert({
      where: { slug: seed.slug },
      create: { name: seed.name, slug: seed.slug, description: seed.description },
      update: {},
      select: { id: true },
    });

    return found.id;
  }

  private async resolveTagIds(names: string[]): Promise<string[]> {
    const ids: string[] = [];

    for (const raw of names.slice(0, 8)) {
      const name = raw.trim().toLowerCase();

      if (!name || name.length > 100) continue;

      const slug = generateSlug(name).slice(0, 100);

      if (!slug) continue;

      const tag = await this.prisma.blogTag.upsert({
        where: { slug },
        create: { name, slug },
        update: {},
        select: { id: true },
      });

      ids.push(tag.id);
    }

    return ids;
  }

  private async writeLog(data: Record<string, any>) {
    try {
      await this.prisma.blogGenerationLog.create({ data: data as any });
    } catch (err) {
      this.logger.warn(`Failed to write generation log: ${(err as Error).message}`);
    }
  }
}
